version: "3"

services:
  portainer:
    image: tomyci/portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
     
  jupyter-notebook:
    hostname: jupyter-notebook
    container_name: jupyter-notebook
    image: tomyci/jupyter-spark-dl-3-6:latest
    command: notebook
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - SPARK_PUBLIC_DNS=localhost
    expose:
      - 4040
      - 8888
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - spark
    links:
      - spark-master
    volumes:
      - d:/sqlday_2019/notebooks:/mnt/notebooks

  spark-master:
    hostname: spark-master
    container_name: jupyter-spark-master
    image: tomyci/jupyter-spark-dl-3-6:latest
    command: master
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WEBUI_PORT=9090
    expose:
      - 6066
      - 7077
      - 9090
    ports:
      - 6066:6066
      - 7077:7077
      - 9090:9090
    networks:
      - spark

  spark-slave-1:
    hostname: spark-slave-1
    container_name: jupyter-spark-slave-1
    image: tomyci/jupyter-spark-dl-3-6:latest
    command: slave
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WEBUI_PORT=9091
      - SPARK_WORKER_PORT=9991
    expose:
      - 9091
      - 9090
      - 9991
    ports:
      - 9091:9091
    networks:
      - spark
    links:
      - spark-master

  spark-slave-2:
    hostname: spark-slave-2
    container_name: jupyter-spark-slave-2
    image: tomyci/jupyter-spark-dl-3-6:latest
    command: slave
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WEBUI_PORT=9092
      - SPARK_WORKER_PORT=9992
    expose:
      - 9092
      - 9090
      - 9992
    ports:
      - 9092:9092
    networks:
      - spark
    links:
      - spark-master
      
volumes:
  portainer_data:
  
networks:
  spark:
    external:
      name: spark 